#!/bin/bash
rm FlyTracker
#/usr/local/lib/fpc/3.3.1/ppca64 FlyTracker.pas -gl -Cio -Fu./FlyCode -Fu./FlyCode/Shared -Fu./FlyCode/Menu -Fu./FlyCode/Tracker -Fu./FlyCode/InstrumentEditor -Fu../../vipgfx-code/src -Fu../../vipgfx-code/TTF/myFT1 -Fu../../tycoonuserinterface-code/src/tuicode -Fu../../tralala-code/src
#fpc FlyTracker.pas -gl -Cio -Fu./FlyCode -Fu../../vipgfx-code/src -Fu../../vipgfx-code/TTF/myFT1 -Fu../../tycoonuserinterface-code/src/tuicode -Fu../../tralala-code/src
/usr/local/lib/fpc/3.3.1/ppca64 FlyTracker.pas -Fu./FlyCode -Fu./FlyCode/Shared -Fu./FlyCode/Menu -Fu./FlyCode/Tracker -Fu./FlyCode/InstrumentEditor -Fu./FlyCode/PianoRoll -Fu./FlyCode/Networking -Fu../../vipgfx-code/src -Fu../../vipgfx-code/TTF/myFT1 -Fu../../tycoonuserinterface-code/src/tuicode -Fu../../tralala-code/src
rm *.o
rm *.ppu
rm ./FlyCode/*.o
rm ./FlyCode/*.ppu
rm ./FlyCode/Menu/*.o
rm ./FlyCode/Menu/*.ppu
rm ./FlyCode/Tracker/*.o
rm ./FlyCode/Tracker/*.ppu
rm ./FlyCode/InstrumentEditor/*.o
rm ./FlyCode/InstrumentEditor/*.ppu
rm ./FlyCode/Shared/*.o
rm ./FlyCode/Shared/*.ppu
rm ./FlyCode/PianoRoll/*.o
rm ./FlyCode/PianoRoll/*.ppu
rm ./FlyCode/Networking/*.o
rm ./FlyCode/Networking/*.ppu
rm ../../vipgfx-code/src/*.o
rm ../../vipgfx-code/src/*.ppu
#rm ../../vipgfx-code/TTF/myFT1/*.o
#rm ../../vipgfx-code/TTF/myFT1/*.ppu
rm ../../tycoonuserinterface-code/src/tuicode/*.o
rm ../../tycoonuserinterface-code/src/tuicode/*.ppu
rm *.res
# 31.18.77.240 my internet IP at home
# 192.168.0.4
# -pf -client31.18.189.13 -port1234 -udp
./FlyTracker my.it -ESC -1 -w -fps 